# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  gcloud: ceddy/gcloud@0.0.2
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own contai
    jobs:
      - welcome/run
      - auth

jobs:
  auth:
    docker:
      - image: google/cloud-sdk:latest-slim
    steps:
      - checkout
      - gcloud/auth:
          service_key: "${FEATURE_DEPLOY_ACCOUNT_KEY}"
          project_id: "${FEATURE_DEPLOY_PROJECT}"
     # - gcloud/gsutil:
     #     cmd: "-m rm -r gs://apples-d8991.appspot.com/${CIRCLE_BRANCH}"
     # - gcloud/gsutil:
     #     cmd: "-m cp -r dist/* gs://apples-d8991.appspot.com/${CIRCLE_BRANCH}"
